# Funding — shows "Sponsor" button on GitHub repo
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [adityatawde9699]
# ko_fi: adityatawde9699
# buy_me_a_coffee: adityatawde9699
# custom: ["https://your-website.com/donate"]
